### PR TITLE
Fix typo in GLUU_REDIS_URL description

### PR DESCRIPTION
**Pull request by skybert**
- upper cased acronym (URL)
- added some Markdown formatting

### CODE REVIEW

**Comment by skybert** [comment]
Ping @iromli

**Comment by iromli** [comment]
@skybert can you pointed your PR to `3.1.1`  branch instead?

**Comment by skybert** [comment]
Did that do the trick @iromli ?

**Comment by iromli** [comment]
Yes.

I will merge to master by myself.

**Pull request merged**
