### PR TITLE
Make openldap container wait for consul to become ready

### PR DESCRIPTION
**Pull request by skybert**
- command that can be called from docker-compose.yml making the
  openldap container hold its horses until the consul container has
  been properly populated (by the config-init container).

- Docker does not have a builtin way of making containers wait for
  others to be "ready", see
  https://docs.docker.com/compose/startup-order/, hence this command.

### CODE REVIEW

**Comment by iromli** [comment]
@skybert can you update the PR just what you did on oxTrust?

**Comment by skybert** [comment]
@iromli, I will do, but I'm awaiting my oxtrust PR to be accepted before I rewrite my other three PRs to make them behave the same way.

The other containers will then have the same wait for it script, with the exception of checking for oxAuth.

**Comment by iromli** [comment]
Your oxTrust PR merged yesterday.

> @iromli, I will do, but I'm awaiting my oxtrust PR to be accepted before I rewrite my other three PRs to make them behave the same way.

**Comment by skybert** [comment]
> @skybert Your oxTrust PR merged yesterday.

My bad, I read the Github inbox in the reverse order (silly me thought the top one was the oldest one, when did that change I wonder?)

**Comment by skybert** [comment]
@iromli, I've updated the docker-openldap PR now. It now uses Python as the others (and only checks for Consul).

**Comment by skybert** [comment]
@iromli : ping?

**Comment by iromli** [comment]
Merged, thanks @skybert

**Pull request merged**
